{pkgs}: {
  deps = [
    pkgs.libjpeg_turbo
    pkgs.libsoup_3
    pkgs.libjxl
    pkgs.gcc
    pkgs.libmanette
    pkgs.nghttp2
    pkgs.libpsl
    pkgs.hyphen
    pkgs.libtasn1
    pkgs.enchant2
    pkgs.wayland
    pkgs.xorg.libX11
    pkgs.expat
    pkgs.fontconfig
    pkgs.freetype
    pkgs.zlib
    pkgs.libpng
    pkgs.libjpeg
    pkgs.libavif
    pkgs.flite
    pkgs.libgpg-error
    pkgs.libgcrypt
    pkgs.systemd
    pkgs.x264
    pkgs.libatomic_ops
    pkgs.libgudev
    pkgs.at-spi2-core
    pkgs.libxkbcommon
    pkgs.woff2
    pkgs.libepoxy
    pkgs.mesa
    pkgs.libdrm
    pkgs.at-spi2-atk
    pkgs.libsecret
    pkgs.libwebp
    pkgs.libopus
    pkgs.libevent
    pkgs.lcms2
    pkgs.libxslt
    pkgs.sqlite
    pkgs.libxml2
    pkgs.icu74
    pkgs.glib
    pkgs.graphene
    pkgs.vulkan-loader
    pkgs.cairo
    pkgs.gdk-pixbuf
    pkgs.harfbuzz
    pkgs.pango
    pkgs.gtk4
    pkgs.gst_all_1.gst-libav
    pkgs.gst_all_1.gst-plugins-bad
    pkgs.gst_all_1.gst-plugins-good
    pkgs.gst_all_1.gst-plugins-base
    pkgs.gst_all_1.gstreamer
  ];
}
