import { Router, type IRouter } from "express";
import healthRouter from "./health";
import orgsRouter from "./orgs";
import meRouter from "./me";
import spendRouter from "./spend";
import suppliersRouter from "./suppliers";
import opportunitiesRouter from "./opportunities";
import cyclesRouter from "./cycles";
import collectorsRouter from "./collectors";
import marketSignalsRouter from "./market-signals";
import intelligenceRouter from "./intelligence";
import jobsRouter from "./jobs";
import ingestRouter from "./ingest";
import billingRouter from "./billing";
import watchedIssuersRouter from "./watched-issuers";
import usSuppliersRouter from "./us-suppliers";
import integrationsRouter from "./integrations";
import adminWhoamiRouter from "./admin-whoami";
import adminUsersRouter from "./admin-users";
import adminApiKeysRouter from "./admin-api-keys";
import adminAuditRouter from "./admin-audit";
import adminDataIntegrityRouter from "./admin-data-integrity";
import adminEngineAccessRouter from "./admin-engine-access";
import adminSsoRouter from "./admin-sso";
import adminTenantRouter from "./admin-tenant";
import adminTrustEngagementRouter from "./admin-trust-engagement";
import adminScimRouter from "./admin-scim";
import scimRouter from "./scim";
import contractsRouter from "./contracts";
import systemRouter from "./system";
import defensePacksRouter from "./defense-packs";
import trustRouter from "./trust";
import alertsRouter from "./alerts";
import readinessRouter from "./readiness";
import onboardingRouter from "./onboarding";
import funnelRouter from "./funnel";
import todayRouter from "./today";
import operationsRouter from "./operations";
import engineHealthRouter from "./engine-health";
import routingRouter from "./routing";
import servicesRouter from "./services";
import sowsRouter from "./sows";
import rateCardsRouter from "./rate-cards";
import methodsAndToolsRouter from "./methods-and-tools";
import adminA11yRouter from "./admin-a11y";

const router: IRouter = Router();

router.use(healthRouter);
router.use(orgsRouter);
router.use(meRouter);
router.use(spendRouter);
router.use(suppliersRouter);
router.use(opportunitiesRouter);
router.use(cyclesRouter);
router.use(collectorsRouter);
router.use(marketSignalsRouter);
router.use(intelligenceRouter);
router.use(jobsRouter);
router.use(ingestRouter);
router.use(billingRouter);
router.use(watchedIssuersRouter);
router.use(usSuppliersRouter);
router.use(integrationsRouter);
router.use(adminWhoamiRouter);
router.use(adminUsersRouter);
router.use(adminApiKeysRouter);
router.use(adminAuditRouter);
router.use(adminDataIntegrityRouter);
router.use(adminEngineAccessRouter);
router.use(adminSsoRouter);
router.use(adminTenantRouter);
router.use(adminTrustEngagementRouter);
router.use(adminScimRouter);
router.use(scimRouter);
router.use(contractsRouter);
router.use(systemRouter);
router.use(defensePacksRouter);
router.use(trustRouter);
router.use(alertsRouter);
router.use(readinessRouter);
router.use(onboardingRouter);
router.use(funnelRouter);
router.use(todayRouter);
router.use(operationsRouter);
router.use(engineHealthRouter);
router.use(routingRouter);
router.use(servicesRouter);
router.use(sowsRouter);
router.use(rateCardsRouter);
router.use(methodsAndToolsRouter);
router.use(adminA11yRouter);

export default router;
