/**
 * Layer A source catalog — strengthened Day 0 map (John: old 8 was weak).
 *
 * Tier 1: implement fetch stubs + schemas for ALL 15 public APIs.
 * Tier 2: file/CSV / careful-page stubs (Cass + SCFI cite-only).
 * Paid commercial feeds: license_required placeholders only.
 * Parallel news/OSINT track: RSS metadata → normalize → dedupe → events.
 * Tier 1.5 gap pack: additional free trade / registry / AIS / relief APIs.
 *
 * No live invented values. No tenant/FSA data. Layer B deferred.
 * Do not store or resell full article HTML as a product payload.
 */

import type { DataFactoryObserveKind } from "./layer-c";

export const dataFactorySourceFamilies = [
  "procurement",
  "index",
  "freight_commodity",
  "disruption",
  "filing",
  "news_osint",
] as const;
export type DataFactorySourceFamily =
  (typeof dataFactorySourceFamilies)[number];

export const dataFactoryLicenseClasses = [
  "public_api",
  "free_registration",
  "paid_license_required",
] as const;
export type DataFactoryLicenseClass =
  (typeof dataFactoryLicenseClasses)[number];

export const dataFactoryFetchStatuses = [
  "wired_existing_collector",
  "stub",
  "license_required",
] as const;
export type DataFactoryFetchStatus =
  (typeof dataFactoryFetchStatuses)[number];

export const dataFactoryDay0Tiers = [
  "tier_1",
  "tier_1_5",
  "tier_1_5b",
  "tier_2",
  "tier_c",
  "news_osint",
  "license_required",
] as const;
export type DataFactoryDay0Tier = (typeof dataFactoryDay0Tiers)[number];

export const dataFactoryChannelUses = ["pulse", "api", "both"] as const;
export type DataFactoryChannelUse = (typeof dataFactoryChannelUses)[number];

export type DataFactoryScrapePosture =
  | "careful_public_page"
  | "file_csv"
  | "socrata"
  | "rss"
  | "fragile_rss"
  | "event_api";

export interface DataFactorySource {
  id: string;
  name: string;
  family: DataFactorySourceFamily;
  observeKind: DataFactoryObserveKind;
  channelUse: DataFactoryChannelUse;
  day0Tier: DataFactoryDay0Tier;
  /** Tier 1 rank 1–15; null otherwise. */
  tierRank: number | null;
  sourceUrl: string;
  feedUrl: string;
  altFeedUrls?: readonly string[];
  licenseClass: DataFactoryLicenseClass;
  licenseNote: string;
  fetchStatus: DataFactoryFetchStatus;
  existingCollectorId: string | null;
  signalTypes: readonly string[];
  scrapePosture?: DataFactoryScrapePosture;
  /** Google News RSS and similar unofficial sensors. */
  fragile?: boolean;
}

/** Strengthened Tier 1 — stubs required for every id. */
export const TIER1_SOURCE_IDS = [
  "src_bls",
  "src_fred",
  "src_eia",
  "src_usda_mymarketnews",
  "src_openfda_food_enforcement",
  "src_openfda_recalls",
  "src_ofac_sdn",
  "src_federal_register",
  "src_sec_edgar",
  "src_bts_teu",
  "src_weather_gov",
  "src_usaspending",
  "src_census_ft900",
  "src_census_m3",
  "src_world_bank_pink_sheet",
  "src_un_comtrade",
] as const;

export const TIER2_SOURCE_IDS = [
  "src_pola",
  "src_polb",
  "src_usgs_mcs",
  "src_usda_ers",
  "src_cpsc",
  "src_beige_book",
  "src_naics",
  "src_unspsc",
  "src_cass_freight_index",
  "src_nhc",
  "src_fda_dashboard",
  "src_sam_gov",
  "src_scfi",
  "src_imf_primary_commodity",
  "src_usace",
  "src_epa_tri",
] as const;

/** Free gap pack — stubs for all of these. GDACS reused from news/OSINT. */
export const TIER15_SOURCE_IDS = [
  "src_wits",
  "src_eurostat",
  "src_eurostat_comext",
  "src_ted_europa",
  "src_opensanctions",
  "src_gleif",
  "src_faostat",
  "src_oecd_sdmx",
  "src_bea",
  "src_reliefweb",
  "src_gdacs",
  "src_opensky",
  "src_aishub",
] as const;

/** Optional 1.5b stubs — John locked 2026-09-16. */
export const TIER15B_SOURCE_IDS = [
  "src_uflpa",
  "src_usitc_trade_remedies",
  "src_usitc_dataweb",
  "src_companies_house",
  "src_wdi",
  "src_panama_canal",
  "src_phmsa",
  "src_wikidata",
  "src_acled",
] as const;

/**
 * Light Tier C backlog stubs. Do not block the PR on live collectors.
 * UK/EU sanctions reuse OpenSanctions.
 */
export const TIER_C_SOURCE_IDS = [
  "src_bis_entity_list",
  "src_bis_denied_persons",
  "src_opensanctions",
  "src_fra",
  "src_stb",
  "src_noaa_ports",
  "src_opencorporates",
  "src_owid",
  "src_uspto_odp",
  "src_ftc_rss",
] as const;

/**
 * Parallel news/OSINT track. Federal Register is reused from Tier 1.
 * Metadata (headline + link) only — no article HTML product payload.
 */
export const NEWS_OSINT_SOURCE_IDS = [
  "src_cbp_csms",
  "src_federal_register",
  "src_freightwaves_rss",
  "src_supply_chain_dive",
  "src_gcaptain",
  "src_maritime_executive",
  "src_splash247",
  "src_loadstar",
  "src_container_news",
  "src_bbc_business",
  "src_gdelt",
  "src_google_news_rss",
  "src_gdacs",
  "src_usgs_quakes",
  "src_nhc_products",
] as const;

export const LICENSE_REQUIRED_PLACEHOLDER_IDS = [
  "src_dat",
  "src_freightos_fbx",
  "src_xeneta",
  "src_drewry",
  "src_sonar",
  "src_lme",
  "src_cme",
  "src_ism_rob",
  "src_sp_commodity_index",
  "src_fastmarkets",
  "src_joc",
] as const;

/** @deprecated use TIER1_SOURCE_IDS — old weak 8-source list */
export const DAY0_WIRE_FIRST_IDS = TIER1_SOURCE_IDS;

export const DATA_FACTORY_SOURCES: readonly DataFactorySource[] = [
  // ---- Tier 1 (strengthened) -------------------------------------------
  {
    id: "src_bls",
    name: "BLS Public Data API v2 (PPI)",
    family: "index",
    observeKind: "price_index",
    channelUse: "both",
    day0Tier: "tier_1",
    tierRank: 1,
    sourceUrl: "https://www.bls.gov/developers/api_signature_v2.htm",
    feedUrl: "https://api.bls.gov/publicAPI/v2/timeseries/data/",
    licenseClass: "public_api",
    licenseNote:
      "BLS v2 public API. Optional BLS_API_KEY raises quota. PPI series (WPU*), not tenant prices.",
    fetchStatus: "wired_existing_collector",
    existingCollectorId: "bls-economic-index",
    signalTypes: ["economic_index"],
  },
  {
    id: "src_fred",
    name: "FRED API",
    family: "index",
    observeKind: "price_index",
    channelUse: "both",
    day0Tier: "tier_1",
    tierRank: 2,
    sourceUrl: "https://fred.stlouisfed.org/docs/api/fred/",
    feedUrl: "https://api.stlouisfed.org/fred/series/observations",
    licenseClass: "free_registration",
    licenseNote: "St. Louis Fed. Production uses FRED_API_KEY. Stub does not call FRED.",
    fetchStatus: "wired_existing_collector",
    existingCollectorId: "fred-economic-index",
    signalTypes: ["economic_index"],
  },
  {
    id: "src_eia",
    name: "EIA Open Data API v2",
    family: "index",
    observeKind: "price_index",
    channelUse: "both",
    day0Tier: "tier_1",
    tierRank: 3,
    sourceUrl: "https://www.eia.gov/opendata/documentation.php",
    feedUrl: "https://api.eia.gov/v2/",
    licenseClass: "free_registration",
    licenseNote: "EIA v2. Production uses EIA_API_KEY.",
    fetchStatus: "wired_existing_collector",
    existingCollectorId: "eia-energy",
    signalTypes: ["commodity_index"],
  },
  {
    id: "src_usda_mymarketnews",
    name: "USDA MyMarketNews API",
    family: "index",
    observeKind: "price_index",
    channelUse: "both",
    day0Tier: "tier_1",
    tierRank: 4,
    // https://mymarketnews.ams.usda.gov/public_data_api
    sourceUrl: "https://mymarketnews.ams.usda.gov/public_data_api",
    feedUrl: "https://marsapi.ams.usda.gov/services/v1.1/reports",
    licenseClass: "free_registration",
    licenseNote:
      "AMS MyMarketNews / MARS API. Free key from USDA AMS. Not USDA NASS QuickStats (separate collector).",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["commodity_index"],
  },
  {
    id: "src_openfda_food_enforcement",
    name: "openFDA food enforcement",
    family: "disruption",
    observeKind: "disruption_policy",
    channelUse: "pulse",
    day0Tier: "tier_1",
    tierRank: 5,
    sourceUrl: "https://open.fda.gov/apis/food/enforcement/",
    feedUrl: "https://api.fda.gov/food/enforcement.json",
    licenseClass: "public_api",
    licenseNote: "FDA openFDA food recall/enforcement. Public events, not a tenant recall list.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["supplier_risk_news"],
  },
  {
    id: "src_openfda_recalls",
    name: "openFDA enforcement recalls (drug/device)",
    family: "disruption",
    observeKind: "disruption_policy",
    channelUse: "pulse",
    day0Tier: "tier_1",
    tierRank: 5,
    sourceUrl: "https://open.fda.gov/apis/",
    feedUrl: "https://api.fda.gov/drug/enforcement.json",
    altFeedUrls: ["https://api.fda.gov/device/enforcement.json"],
    licenseClass: "public_api",
    licenseNote: "openFDA enforcement JSON for drug and device recalls.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["supplier_risk_news"],
  },
  {
    id: "src_ofac_sdn",
    name: "OFAC SDN CSV/XML downloads",
    family: "disruption",
    observeKind: "disruption_policy",
    channelUse: "both",
    day0Tier: "tier_1",
    tierRank: 6,
    sourceUrl: "https://ofac.treasury.gov/sanctions-list-service",
    feedUrl: "https://www.treasury.gov/ofac/downloads/sdn.xml",
    altFeedUrls: [
      "https://www.treasury.gov/ofac/downloads/sdn.csv",
      "https://www.treasury.gov/ofac/downloads/sdn_advanced.xml",
    ],
    licenseClass: "public_api",
    licenseNote:
      "Treasury SDN XML + CSV. Not a screening-product claim. Existing `government-sanctions` already pulls XML.",
    fetchStatus: "wired_existing_collector",
    existingCollectorId: "government-sanctions",
    signalTypes: ["sanctions_match"],
  },
  {
    id: "src_federal_register",
    name: "Federal Register API",
    family: "disruption",
    observeKind: "disruption_policy",
    channelUse: "pulse",
    day0Tier: "tier_1",
    tierRank: 7,
    sourceUrl: "https://www.federalregister.gov/developers/documentation/api/v1",
    feedUrl: "https://www.federalregister.gov/api/v1/documents.json",
    altFeedUrls: [
      "https://www.federalregister.gov/api/v1/documents.rss",
    ],
    licenseClass: "public_api",
    licenseNote: "NARA Federal Register v1. Public rules/notices — policy disruption, not tenant dockets.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["event_geocoded"],
  },
  {
    id: "src_sec_edgar",
    name: "SEC EDGAR APIs",
    family: "filing",
    observeKind: "supplier_public",
    channelUse: "api",
    day0Tier: "tier_1",
    tierRank: 8,
    sourceUrl: "https://www.sec.gov/os/accessing-edgar-data",
    feedUrl: "https://data.sec.gov/submissions/",
    altFeedUrls: [
      "https://efts.sec.gov/LATEST/search-index",
      "https://data.sec.gov/api/xbrl/companyfacts/",
    ],
    licenseClass: "public_api",
    licenseNote: "SEC fair-access User-Agent required (SEC_EDGAR_USER_AGENT).",
    fetchStatus: "wired_existing_collector",
    existingCollectorId: "sec-edgar",
    signalTypes: ["corporate_filing"],
  },
  {
    id: "src_bts_teu",
    name: "BTS data.bts.gov Monthly TEU (Socrata)",
    family: "freight_commodity",
    observeKind: "logistics_lane",
    channelUse: "both",
    day0Tier: "tier_1",
    tierRank: 9,
    sourceUrl: "https://www.bts.gov/PPFS",
    feedUrl: "https://data.bts.gov/",
    altFeedUrls: ["https://data.bts.gov/browse?q=TEU"],
    licenseClass: "public_api",
    licenseNote:
      "Socrata `https://data.bts.gov/resource/{id}.json`. Pin the monthly TEU 4×4 dataset id before live fetch — do not invent an id.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["freight_rate"],
    scrapePosture: "socrata",
  },
  {
    id: "src_weather_gov",
    name: "api.weather.gov alerts",
    family: "disruption",
    observeKind: "disruption_policy",
    channelUse: "pulse",
    day0Tier: "tier_1",
    tierRank: 10,
    sourceUrl: "https://www.weather.gov/documentation/services-web-api",
    feedUrl: "https://api.weather.gov/alerts/active",
    licenseClass: "public_api",
    licenseNote: "NWS public API. Contact User-Agent required.",
    fetchStatus: "stub",
    existingCollectorId: "natural-hazards",
    signalTypes: ["natural_hazard"],
  },
  {
    id: "src_usaspending",
    name: "USAspending.gov API",
    family: "procurement",
    observeKind: "disruption_policy",
    channelUse: "api",
    day0Tier: "tier_1",
    tierRank: 11,
    sourceUrl: "https://api.usaspending.gov/",
    feedUrl: "https://api.usaspending.gov/api/v2/search/spending_by_award/",
    licenseClass: "public_api",
    licenseNote: "Award-level public records. Not tenant spend.",
    fetchStatus: "wired_existing_collector",
    existingCollectorId: "usaspending",
    signalTypes: ["public_bid_award"],
  },
  {
    id: "src_census_ft900",
    name: "Census Foreign Trade / FT-900 downloads",
    family: "freight_commodity",
    observeKind: "logistics_lane",
    channelUse: "both",
    day0Tier: "tier_1",
    tierRank: 12,
    sourceUrl:
      "https://www.census.gov/foreign-trade/Press-Release/current_press_release/index.html",
    feedUrl:
      "https://www.census.gov/foreign-trade/Press-Release/current_press_release/index.html",
    licenseClass: "public_api",
    licenseNote:
      "Monthly FT-900 exhibits (XLS/CSV). US government work. Stub does not invent trade balances.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["customs_trade"],
    scrapePosture: "file_csv",
  },
  {
    id: "src_census_m3",
    name: "Census M3 (Manufacturers' Shipments)",
    family: "index",
    observeKind: "price_index",
    channelUse: "both",
    day0Tier: "tier_1",
    tierRank: 13,
    sourceUrl: "https://www.census.gov/manufacturing/m3/index.html",
    feedUrl: "https://api.census.gov/data/timeseries/eits/m3",
    altFeedUrls: [
      "https://www.census.gov/manufacturing/m3/historical_data/index.html",
    ],
    licenseClass: "public_api",
    licenseNote: "Census EITS M3 timeseries. Optional CENSUS_API_KEY.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["economic_index"],
  },
  {
    id: "src_world_bank_pink_sheet",
    name: "World Bank Pink Sheet commodity monthly",
    family: "index",
    observeKind: "price_index",
    channelUse: "both",
    day0Tier: "tier_1",
    tierRank: 14,
    sourceUrl: "https://www.worldbank.org/en/research/commodity-markets",
    feedUrl:
      "https://thedocs.worldbank.org/en/doc/5d903e848db1d1b83e0ec8f744e55570-0350012021/related/CMO-Historical-Data-Monthly.xlsx",
    licenseClass: "public_api",
    licenseNote: "World Bank CMO monthly XLSX. Cite World Bank.",
    fetchStatus: "wired_existing_collector",
    existingCollectorId: "world-bank-pink-sheet",
    signalTypes: ["commodity_index"],
    scrapePosture: "file_csv",
  },
  {
    id: "src_un_comtrade",
    name: "UN Comtrade free tier / bulk",
    family: "freight_commodity",
    observeKind: "logistics_lane",
    channelUse: "both",
    day0Tier: "tier_1",
    tierRank: 15,
    sourceUrl: "https://comtradedeveloper.un.org/",
    feedUrl: "https://comtradeapi.un.org/public/v1",
    altFeedUrls: [
      "https://comtrade.un.org/data/dev/portal",
      "https://comtradeplus.un.org/",
    ],
    licenseClass: "free_registration",
    licenseNote:
      "Comtrade Plus free tier needs a subscription key. Use public/bulk only where the terms allow. No paid extract.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["customs_trade"],
  },

  // ---- Tier 2 file / CSV / careful pages --------------------------------
  {
    id: "src_pola",
    name: "Port of Los Angeles statistics",
    family: "freight_commodity",
    observeKind: "logistics_lane",
    channelUse: "pulse",
    day0Tier: "tier_2",
    tierRank: null,
    sourceUrl: "https://www.portoflosangeles.org/business/statistics",
    feedUrl:
      "https://www.portoflosangeles.org/business/statistics/container-statistics",
    licenseClass: "public_api",
    licenseNote: "Public HTML/CSV. Careful scrape later. No invented TEU.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["freight_rate"],
    scrapePosture: "careful_public_page",
  },
  {
    id: "src_polb",
    name: "Port of Long Beach statistics",
    family: "freight_commodity",
    observeKind: "logistics_lane",
    channelUse: "pulse",
    day0Tier: "tier_2",
    tierRank: null,
    sourceUrl: "https://polb.com/business/port-statistics/",
    feedUrl: "https://polb.com/business/port-statistics/",
    licenseClass: "public_api",
    licenseNote: "Public HTML/CSV. Careful scrape later.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["freight_rate"],
    scrapePosture: "careful_public_page",
  },
  {
    id: "src_usgs_mcs",
    name: "USGS Mineral Commodity Summaries",
    family: "index",
    observeKind: "price_index",
    channelUse: "both",
    day0Tier: "tier_2",
    tierRank: null,
    sourceUrl:
      "https://www.usgs.gov/centers/national-minerals-information-center/commodity-statistics-and-information",
    feedUrl:
      "https://www.usgs.gov/centers/national-minerals-information-center",
    licenseClass: "public_api",
    licenseNote: "USGS MCS annual files. Existing collector `usgs-mineral`.",
    fetchStatus: "wired_existing_collector",
    existingCollectorId: "usgs-mineral",
    signalTypes: ["commodity_index"],
    scrapePosture: "file_csv",
  },
  {
    id: "src_usda_ers",
    name: "USDA ERS data products",
    family: "index",
    observeKind: "price_index",
    channelUse: "both",
    day0Tier: "tier_2",
    tierRank: null,
    sourceUrl: "https://www.ers.usda.gov/data-products",
    feedUrl: "https://www.ers.usda.gov/data-products",
    licenseClass: "public_api",
    licenseNote: "ERS public data products (XLS/CSV). Pin a product before live fetch.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["economic_index"],
    scrapePosture: "file_csv",
  },
  {
    id: "src_cpsc",
    name: "CPSC / SaferProducts recalls",
    family: "disruption",
    observeKind: "disruption_policy",
    channelUse: "pulse",
    day0Tier: "tier_2",
    tierRank: null,
    sourceUrl: "https://www.cpsc.gov/Recalls",
    feedUrl: "https://www.saferproducts.gov/RestWebServices/Recall",
    licenseClass: "public_api",
    licenseNote: "CPSC public recall web service.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["supplier_risk_news"],
  },
  {
    id: "src_beige_book",
    name: "Fed Beige Book",
    family: "index",
    observeKind: "price_index",
    channelUse: "pulse",
    day0Tier: "tier_2",
    tierRank: null,
    sourceUrl:
      "https://www.federalreserve.gov/monetarypolicy/beige-book-default.htm",
    feedUrl:
      "https://www.federalreserve.gov/monetarypolicy/beige-book-default.htm",
    licenseClass: "public_api",
    licenseNote: "HTML/PDF qualitative report. No invented PMI numbers.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["economic_index"],
    scrapePosture: "careful_public_page",
  },
  {
    id: "src_naics",
    name: "NAICS codes",
    family: "procurement",
    observeKind: "supplier_public",
    channelUse: "api",
    day0Tier: "tier_2",
    tierRank: null,
    sourceUrl: "https://www.census.gov/naics/",
    feedUrl: "https://www.census.gov/naics/",
    licenseClass: "public_api",
    licenseNote: "Census NAICS concordance downloads. Taxonomy, not a price feed.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["entity_registry"],
    scrapePosture: "file_csv",
  },
  {
    id: "src_unspsc",
    name: "UNSPSC codes",
    family: "procurement",
    observeKind: "supplier_public",
    channelUse: "api",
    day0Tier: "tier_2",
    tierRank: null,
    sourceUrl: "https://www.unspsc.org/",
    feedUrl: "https://www.unspsc.org/download-unspsc",
    licenseClass: "free_registration",
    licenseNote:
      "UNSPSC download often requires registration. Confirm terms before redistributing codes.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["entity_registry"],
    scrapePosture: "file_csv",
  },
  {
    id: "src_cass_freight_index",
    name: "Cass Freight Index",
    family: "freight_commodity",
    observeKind: "logistics_lane",
    channelUse: "both",
    day0Tier: "tier_2",
    tierRank: null,
    sourceUrl:
      "https://www.cassinfo.com/freight-audit-payment/cass-transportation-indexes",
    feedUrl:
      "https://www.cassinfo.com/freight-audit-payment/cass-transportation-indexes",
    licenseClass: "paid_license_required",
    licenseNote: "Cite-only until a human-approved license is on file.",
    fetchStatus: "license_required",
    existingCollectorId: null,
    signalTypes: ["freight_rate"],
  },
  {
    id: "src_nhc",
    name: "NHC tropical cyclone GIS",
    family: "disruption",
    observeKind: "disruption_policy",
    channelUse: "pulse",
    day0Tier: "tier_2",
    tierRank: null,
    sourceUrl: "https://www.nhc.noaa.gov/",
    feedUrl: "https://www.nhc.noaa.gov/gis/",
    licenseClass: "public_api",
    licenseNote: "NOAA NHC public GIS / advisories.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["natural_hazard"],
    scrapePosture: "file_csv",
  },
  {
    id: "src_fda_dashboard",
    name: "FDA recalls dashboard",
    family: "disruption",
    observeKind: "disruption_policy",
    channelUse: "pulse",
    day0Tier: "tier_2",
    tierRank: null,
    sourceUrl: "https://datadashboard.fda.gov/ora/cd/recalls.htm",
    feedUrl: "https://datadashboard.fda.gov/ora/cd/recalls.htm",
    altFeedUrls: [
      "https://www.fda.gov/safety/recalls-market-withdrawals-safety-alerts",
    ],
    licenseClass: "public_api",
    licenseNote: "Public dashboard / HTML. Prefer openFDA APIs (Tier 1) for machine reads.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["supplier_risk_news"],
    scrapePosture: "careful_public_page",
  },
  {
    id: "src_sam_gov",
    name: "SAM.gov opportunities (careful)",
    family: "procurement",
    observeKind: "disruption_policy",
    channelUse: "api",
    day0Tier: "tier_2",
    tierRank: null,
    sourceUrl: "https://open.gsa.gov/api/opportunities-api/",
    feedUrl: "https://api.sam.gov/opportunities/v2/search",
    licenseClass: "free_registration",
    licenseNote:
      "Public opportunities. Rate-limit + SAM_GOV_API_KEY. Careful — ToS and quota. Existing `sam-gov` collector.",
    fetchStatus: "wired_existing_collector",
    existingCollectorId: "sam-gov",
    signalTypes: ["public_bid_award"],
  },
  {
    id: "src_scfi",
    name: "Shanghai Containerized Freight Index (SCFI)",
    family: "freight_commodity",
    observeKind: "logistics_lane",
    channelUse: "both",
    day0Tier: "tier_2",
    tierRank: null,
    sourceUrl: "https://en.sse.net.cn/",
    feedUrl: "https://en.sse.net.cn/",
    licenseClass: "paid_license_required",
    licenseNote: "Cite-only. Do not scrape SSE/SCFI.",
    fetchStatus: "license_required",
    existingCollectorId: null,
    signalTypes: ["freight_rate"],
  },
  {
    id: "src_imf_primary_commodity",
    name: "IMF primary commodity prices",
    family: "index",
    observeKind: "price_index",
    channelUse: "both",
    day0Tier: "tier_2",
    tierRank: null,
    sourceUrl: "https://www.imf.org/en/Research/commodity-prices",
    feedUrl: "https://www.imf.org/en/Research/commodity-prices",
    licenseClass: "public_api",
    licenseNote: "IMF monthly commodity XLS. Cite IMF. No invented indexes.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["commodity_index"],
    scrapePosture: "file_csv",
  },
  {
    id: "src_usace",
    name: "USACE waterborne commerce (if open)",
    family: "freight_commodity",
    observeKind: "logistics_lane",
    channelUse: "both",
    day0Tier: "tier_2",
    tierRank: null,
    sourceUrl:
      "https://www.iwr.usace.army.mil/About/Technical-Centers/WCSC-Waterborne-Commerce-Statistics-Center/",
    feedUrl:
      "https://www.iwr.usace.army.mil/About/Technical-Centers/WCSC-Waterborne-Commerce-Statistics-Center/",
    licenseClass: "public_api",
    licenseNote:
      "WCSC reports are often public PDFs/tables. Confirm the specific open file before fetch. Skip if not open.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["freight_rate"],
    scrapePosture: "file_csv",
  },
  {
    id: "src_epa_tri",
    name: "EPA Toxics Release Inventory",
    family: "disruption",
    observeKind: "disruption_policy",
    channelUse: "both",
    day0Tier: "tier_2",
    tierRank: null,
    sourceUrl: "https://www.epa.gov/toxics-release-inventory-tri-program",
    feedUrl: "https://www.epa.gov/toxics-release-inventory-tri-program/tri-basic-data-files-calendar-years-1987-present",
    altFeedUrls: ["https://data.epa.gov/efservice/"],
    licenseClass: "public_api",
    licenseNote: "TRI basic data files / Envirofacts. Facility releases, not tenant EHS data.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["environmental_violation"],
    scrapePosture: "file_csv",
  },

  // ---- Parallel news / OSINT (RSS metadata only) ------------------------
  {
    id: "src_cbp_csms",
    name: "CBP CSMS / GovDelivery (if public)",
    family: "news_osint",
    observeKind: "disruption_policy",
    channelUse: "pulse",
    day0Tier: "news_osint",
    tierRank: null,
    sourceUrl:
      "https://www.cbp.gov/trade/automated/cargo-systems-messaging-service",
    feedUrl: "https://content.govdelivery.com/accounts/USDHSCBP/bulletins.rss",
    licenseClass: "public_api",
    licenseNote:
      "Stub only if the GovDelivery bulletin RSS is publicly readable. Confirm before live fetch. Headlines + link; no CSMS body republish.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["osint_headline"],
    scrapePosture: "rss",
  },
  {
    id: "src_freightwaves_rss",
    name: "FreightWaves RSS",
    family: "news_osint",
    observeKind: "logistics_lane",
    channelUse: "pulse",
    day0Tier: "news_osint",
    tierRank: null,
    sourceUrl: "https://www.freightwaves.com/",
    feedUrl: "https://www.freightwaves.com/feed",
    licenseClass: "public_api",
    licenseNote:
      "Site RSS. Headlines + link only. Not SONAR (that stays license_required). No article HTML.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["osint_headline"],
    scrapePosture: "rss",
  },
  {
    id: "src_supply_chain_dive",
    name: "Supply Chain Dive RSS",
    family: "news_osint",
    observeKind: "disruption_policy",
    channelUse: "pulse",
    day0Tier: "news_osint",
    tierRank: null,
    sourceUrl: "https://www.supplychaindive.com/",
    feedUrl: "https://www.supplychaindive.com/feeds/news/",
    licenseClass: "public_api",
    licenseNote: "Industry RSS. Cite headline + URL. Full-text republish is out of scope.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["osint_headline"],
    scrapePosture: "rss",
  },
  {
    id: "src_gcaptain",
    name: "gCaptain RSS",
    family: "news_osint",
    observeKind: "logistics_lane",
    channelUse: "pulse",
    day0Tier: "news_osint",
    tierRank: null,
    sourceUrl: "https://gcaptain.com/",
    feedUrl: "https://gcaptain.com/feed/",
    licenseClass: "public_api",
    licenseNote: "Maritime RSS. Headlines + link only.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["osint_headline"],
    scrapePosture: "rss",
  },
  {
    id: "src_maritime_executive",
    name: "Maritime Executive RSS",
    family: "news_osint",
    observeKind: "logistics_lane",
    channelUse: "pulse",
    day0Tier: "news_osint",
    tierRank: null,
    sourceUrl: "https://www.maritime-executive.com/",
    feedUrl: "https://www.maritime-executive.com/rss.xml",
    licenseClass: "public_api",
    licenseNote: "Maritime RSS. Headlines + link only.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["osint_headline"],
    scrapePosture: "rss",
  },
  {
    id: "src_splash247",
    name: "Splash247 RSS",
    family: "news_osint",
    observeKind: "logistics_lane",
    channelUse: "pulse",
    day0Tier: "news_osint",
    tierRank: null,
    sourceUrl: "https://splash247.com/",
    feedUrl: "https://splash247.com/feed/",
    licenseClass: "public_api",
    licenseNote: "Maritime RSS. Headlines + link only.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["osint_headline"],
    scrapePosture: "rss",
  },
  {
    id: "src_loadstar",
    name: "The Loadstar RSS",
    family: "news_osint",
    observeKind: "logistics_lane",
    channelUse: "pulse",
    day0Tier: "news_osint",
    tierRank: null,
    sourceUrl: "https://theloadstar.com/",
    feedUrl: "https://theloadstar.com/feed/",
    licenseClass: "public_api",
    licenseNote: "Freight RSS. Headlines + link only.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["osint_headline"],
    scrapePosture: "rss",
  },
  {
    id: "src_container_news",
    name: "Container News RSS",
    family: "news_osint",
    observeKind: "logistics_lane",
    channelUse: "pulse",
    day0Tier: "news_osint",
    tierRank: null,
    sourceUrl: "https://container-news.com/",
    feedUrl: "https://container-news.com/feed/",
    licenseClass: "public_api",
    licenseNote: "Container-shipping RSS. Headlines + link only.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["osint_headline"],
    scrapePosture: "rss",
  },
  {
    id: "src_bbc_business",
    name: "BBC Business RSS",
    family: "news_osint",
    observeKind: "disruption_policy",
    channelUse: "pulse",
    day0Tier: "news_osint",
    tierRank: null,
    sourceUrl: "https://www.bbc.com/news/business",
    feedUrl: "https://feeds.bbci.co.uk/news/business/rss.xml",
    licenseClass: "public_api",
    licenseNote:
      "BBC RSS. Headline + link per BBC syndication terms. Do not republish full text.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["osint_headline"],
    scrapePosture: "rss",
  },
  {
    id: "src_gdelt",
    name: "GDELT 2.0 DOC API",
    family: "news_osint",
    observeKind: "disruption_policy",
    channelUse: "both",
    day0Tier: "news_osint",
    tierRank: null,
    sourceUrl: "https://www.gdeltproject.org/",
    feedUrl: "https://api.gdeltproject.org/api/v2/doc/doc",
    licenseClass: "public_api",
    licenseNote:
      "GDELT event/doc graph. Metadata + source URLs. Do not store article HTML from linked publishers.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["osint_headline"],
    scrapePosture: "event_api",
  },
  {
    id: "src_google_news_rss",
    name: "Google News RSS (optional / fragile)",
    family: "news_osint",
    observeKind: "disruption_policy",
    channelUse: "pulse",
    day0Tier: "news_osint",
    tierRank: null,
    sourceUrl: "https://news.google.com/",
    feedUrl: "https://news.google.com/rss/search",
    licenseClass: "public_api",
    licenseNote:
      "Optional targeted query sensor. Unofficial RSS — mark fragile. Do not depend on it for GA. Headlines + link only.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["osint_headline"],
    scrapePosture: "fragile_rss",
    fragile: true,
  },
  {
    id: "src_gdacs",
    name: "GDACS disaster RSS",
    family: "news_osint",
    observeKind: "disruption_policy",
    channelUse: "pulse",
    day0Tier: "news_osint",
    tierRank: null,
    sourceUrl: "https://www.gdacs.org/",
    feedUrl: "https://www.gdacs.org/xml/rss.xml",
    licenseClass: "public_api",
    licenseNote: "UN/EC Joint Research Centre GDACS public RSS. Event metadata.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["osint_headline"],
    scrapePosture: "rss",
  },
  {
    id: "src_usgs_quakes",
    name: "USGS significant earthquakes",
    family: "news_osint",
    observeKind: "disruption_policy",
    channelUse: "pulse",
    day0Tier: "news_osint",
    tierRank: null,
    sourceUrl: "https://earthquake.usgs.gov/earthquakes/feed/",
    feedUrl:
      "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/significant_week.atom",
    altFeedUrls: [
      "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/significant_week.geojson",
    ],
    licenseClass: "public_api",
    licenseNote: "USGS significant-quake Atom/GeoJSON. Distinct from USGS MCS (Tier 2).",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["osint_headline"],
    scrapePosture: "rss",
  },
  {
    id: "src_nhc_products",
    name: "NHC advisory products",
    family: "news_osint",
    observeKind: "disruption_policy",
    channelUse: "pulse",
    day0Tier: "news_osint",
    tierRank: null,
    sourceUrl: "https://www.nhc.noaa.gov/",
    feedUrl: "https://www.nhc.noaa.gov/index-at.xml",
    altFeedUrls: [
      "https://www.nhc.noaa.gov/index-ep.xml",
      "https://www.nhc.noaa.gov/gis/",
    ],
    licenseClass: "public_api",
    licenseNote:
      "NHC public advisory XML. Complements Tier 2 `src_nhc` GIS files. Product metadata, not a scraped article.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["osint_headline"],
    scrapePosture: "rss",
  },

  // ---- Tier 1.5 gap pack (free) ----------------------------------------
  {
    id: "src_wits",
    name: "World Bank WITS",
    family: "freight_commodity",
    observeKind: "logistics_lane",
    channelUse: "both",
    day0Tier: "tier_1_5",
    tierRank: null,
    sourceUrl: "https://wits.worldbank.org/witsapi.html",
    feedUrl: "https://wits.worldbank.org/API/V1/SMX/wits/datasource",
    licenseClass: "public_api",
    licenseNote:
      "WITS public API. Trade-value metadata. Complements UN Comtrade. No invented HS values.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["customs_trade"],
  },
  {
    id: "src_eurostat",
    name: "Eurostat dissemination API",
    family: "index",
    observeKind: "price_index",
    channelUse: "both",
    day0Tier: "tier_1_5",
    tierRank: null,
    sourceUrl: "https://ec.europa.eu/eurostat/web/main/data/database",
    feedUrl:
      "https://ec.europa.eu/eurostat/api/dissemination/statistics/1.0/data/",
    licenseClass: "public_api",
    licenseNote: "Eurostat REST, no key. Existing collector `eurostat-economic-index`.",
    fetchStatus: "wired_existing_collector",
    existingCollectorId: "eurostat-economic-index",
    signalTypes: ["economic_index"],
  },
  {
    id: "src_eurostat_comext",
    name: "Eurostat Comext (extra-EU trade)",
    family: "freight_commodity",
    observeKind: "logistics_lane",
    channelUse: "both",
    day0Tier: "tier_1_5",
    tierRank: null,
    sourceUrl:
      "https://ec.europa.eu/eurostat/web/international-trade-in-goods/data",
    feedUrl:
      "https://ec.europa.eu/eurostat/api/comext/dissemination/sdmx/2.1/data/",
    licenseClass: "public_api",
    licenseNote:
      "Comext / international-trade-in-goods. Distinct from the Eurostat PPI/HICP collector. Stub only.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["customs_trade"],
  },
  {
    id: "src_ted_europa",
    name: "TED Europa (Tenders Electronic Daily)",
    family: "procurement",
    observeKind: "disruption_policy",
    channelUse: "api",
    day0Tier: "tier_1_5",
    tierRank: null,
    sourceUrl: "https://ted.europa.eu/",
    feedUrl: "https://api.ted.europa.eu/v3/notices/search",
    licenseClass: "public_api",
    licenseNote: "EU public procurement notices. Not tenant RFPs.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["public_bid_award"],
  },
  {
    id: "src_opensanctions",
    name: "OpenSanctions",
    family: "disruption",
    observeKind: "disruption_policy",
    channelUse: "both",
    day0Tier: "tier_1_5",
    tierRank: null,
    sourceUrl: "https://www.opensanctions.org/",
    feedUrl:
      "https://data.opensanctions.org/datasets/latest/default/entities.ftm.json",
    licenseClass: "public_api",
    licenseNote:
      "CC-BY bulk FollowTheMoney. Existing collector `opensanctions`. Not a screening-product claim.",
    fetchStatus: "wired_existing_collector",
    existingCollectorId: "opensanctions",
    signalTypes: ["risk_screening_match"],
  },
  {
    id: "src_gleif",
    name: "GLEIF LEI records",
    family: "filing",
    observeKind: "supplier_public",
    channelUse: "api",
    day0Tier: "tier_1_5",
    tierRank: null,
    sourceUrl: "https://www.gleif.org/en/lei-data/gleif-api",
    feedUrl: "https://api.gleif.org/api/v1/lei-records",
    licenseClass: "public_api",
    licenseNote: "GLEIF JSON:API, CC0. Existing collector `gleif-lei`.",
    fetchStatus: "wired_existing_collector",
    existingCollectorId: "gleif-lei",
    signalTypes: ["entity_registry"],
  },
  {
    id: "src_faostat",
    name: "FAOSTAT",
    family: "index",
    observeKind: "price_index",
    channelUse: "both",
    day0Tier: "tier_1_5",
    tierRank: null,
    sourceUrl: "https://www.fao.org/faostat/en/#data",
    feedUrl: "https://fenixservices.fao.org/faostat/api/v1/en/",
    licenseClass: "public_api",
    licenseNote: "FAO commodity / food-price domains. Cite FAO. No invented prices.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["commodity_index"],
  },
  {
    id: "src_oecd_sdmx",
    name: "OECD SDMX",
    family: "index",
    observeKind: "price_index",
    channelUse: "both",
    day0Tier: "tier_1_5",
    tierRank: null,
    sourceUrl: "https://data.oecd.org/",
    feedUrl: "https://sdmx.oecd.org/public/rest/data",
    licenseClass: "public_api",
    licenseNote: "OECD SDMX-JSON REST. Free reuse with attribution.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["economic_index"],
  },
  {
    id: "src_bea",
    name: "BEA API",
    family: "index",
    observeKind: "price_index",
    channelUse: "both",
    day0Tier: "tier_1_5",
    tierRank: null,
    sourceUrl: "https://apps.bea.gov/api/signup/",
    feedUrl: "https://apps.bea.gov/api/data",
    licenseClass: "free_registration",
    licenseNote: "US Bureau of Economic Analysis. Production uses BEA_API_KEY.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["economic_index"],
  },
  {
    id: "src_reliefweb",
    name: "ReliefWeb API",
    family: "disruption",
    observeKind: "disruption_policy",
    channelUse: "pulse",
    day0Tier: "tier_1_5",
    tierRank: null,
    sourceUrl: "https://apidoc.reliefweb.int/",
    feedUrl: "https://api.reliefweb.int/v2/disasters",
    altFeedUrls: ["https://api.reliefweb.int/v2/reports"],
    licenseClass: "public_api",
    licenseNote:
      "OCHA ReliefWeb disasters/reports. Metadata + links. Complements GDACS.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["natural_hazard"],
  },
  {
    id: "src_opensky",
    name: "OpenSky Network",
    family: "freight_commodity",
    observeKind: "logistics_lane",
    channelUse: "pulse",
    day0Tier: "tier_1_5",
    tierRank: null,
    sourceUrl: "https://opensky-network.org/",
    feedUrl: "https://opensky-network.org/api/states/all",
    licenseClass: "public_api",
    licenseNote:
      "Free OpenSky REST (anonymous rate-limited). Air-traffic states, not a paid ADS-B product.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["freight_rate"],
  },
  {
    id: "src_aishub",
    name: "AISHub (free AIS only)",
    family: "freight_commodity",
    observeKind: "logistics_lane",
    channelUse: "both",
    day0Tier: "tier_1_5",
    tierRank: null,
    sourceUrl: "https://www.aishub.net/api",
    feedUrl: "https://www.aishub.net/api",
    licenseClass: "free_registration",
    licenseNote:
      "Contributor / free AISHub API only. Do not add MarineTraffic (paid).",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["freight_rate"],
  },

  // ---- Optional Tier 1.5b ----------------------------------------------
  {
    id: "src_uflpa",
    name: "UFLPA entity list",
    family: "disruption",
    observeKind: "disruption_policy",
    channelUse: "both",
    day0Tier: "tier_1_5b",
    tierRank: null,
    sourceUrl: "https://www.dhs.gov/uflpa-entity-list",
    feedUrl: "https://www.dhs.gov/uflpa-entity-list",
    licenseClass: "public_api",
    licenseNote:
      "DHS UFLPA entity list (HTML/CSV). Careful public page. Named entities only.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["sanctions_match"],
    scrapePosture: "careful_public_page",
  },
  {
    id: "src_usitc_trade_remedies",
    name: "USITC / ITA trade remedies",
    family: "disruption",
    observeKind: "disruption_policy",
    channelUse: "api",
    day0Tier: "tier_1_5b",
    tierRank: null,
    sourceUrl: "https://www.usitc.gov/trade_remedy",
    feedUrl: "https://www.usitc.gov/trade_remedy",
    altFeedUrls: [
      "https://www.trade.gov/data-visualization/adcvd-proceedings",
    ],
    licenseClass: "public_api",
    licenseNote: "AD/CVD investigations. Public docket metadata, not tenant cases.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["event_geocoded"],
    scrapePosture: "careful_public_page",
  },
  {
    id: "src_usitc_dataweb",
    name: "USITC DataWeb / HTS",
    family: "freight_commodity",
    observeKind: "logistics_lane",
    channelUse: "both",
    day0Tier: "tier_1_5b",
    tierRank: null,
    sourceUrl: "https://dataweb.usitc.gov/",
    feedUrl: "https://dataweb.usitc.gov/",
    altFeedUrls: ["https://hts.usitc.gov/"],
    licenseClass: "free_registration",
    licenseNote:
      "USITC DataWeb trade extracts + Harmonized Tariff Schedule. Free registration for DataWeb. No invented HS values.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["customs_trade"],
    scrapePosture: "file_csv",
  },
  {
    id: "src_companies_house",
    name: "Companies House",
    family: "filing",
    observeKind: "supplier_public",
    channelUse: "api",
    day0Tier: "tier_1_5b",
    tierRank: null,
    sourceUrl: "https://developer.company-information.service.gov.uk/",
    feedUrl: "https://api.company-information.service.gov.uk/company/",
    licenseClass: "free_registration",
    licenseNote:
      "UK CH filing history. Free key COMPANIES_HOUSE_API_KEY. Existing collector `companies-house`.",
    fetchStatus: "wired_existing_collector",
    existingCollectorId: "companies-house",
    signalTypes: ["corporate_filing"],
  },
  {
    id: "src_wdi",
    name: "World Bank WDI",
    family: "index",
    observeKind: "price_index",
    channelUse: "both",
    day0Tier: "tier_1_5b",
    tierRank: null,
    sourceUrl: "https://data.worldbank.org/",
    feedUrl: "https://api.worldbank.org/v2/country/all/indicator/",
    licenseClass: "public_api",
    licenseNote:
      "World Development Indicators. Distinct from Pink Sheet commodities.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["economic_index"],
  },
  {
    id: "src_panama_canal",
    name: "Panama Canal advisories",
    family: "freight_commodity",
    observeKind: "logistics_lane",
    channelUse: "pulse",
    day0Tier: "tier_1_5b",
    tierRank: null,
    sourceUrl: "https://pancanal.com/en/",
    feedUrl: "https://pancanal.com/en/",
    licenseClass: "public_api",
    licenseNote: "Cite-only public advisories. No invented transit restrictions.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["freight_rate"],
    scrapePosture: "careful_public_page",
  },
  {
    id: "src_phmsa",
    name: "PHMSA incident / hazmat data",
    family: "disruption",
    observeKind: "disruption_policy",
    channelUse: "pulse",
    day0Tier: "tier_1_5b",
    tierRank: null,
    sourceUrl: "https://www.phmsa.dot.gov/data-and-statistics/pipeline/data-and-statistics-overview",
    feedUrl:
      "https://www.phmsa.dot.gov/data-and-statistics/pipeline/source-data",
    licenseClass: "public_api",
    licenseNote: "DOT PHMSA public incident files. Not tenant EHS data.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["environmental_violation"],
    scrapePosture: "file_csv",
  },
  {
    id: "src_wikidata",
    name: "Wikidata reconcile helper",
    family: "filing",
    observeKind: "supplier_public",
    channelUse: "api",
    day0Tier: "tier_1_5b",
    tierRank: null,
    sourceUrl: "https://www.wikidata.org/wiki/Wikidata:Data_access",
    feedUrl: "https://query.wikidata.org/sparql",
    altFeedUrls: ["https://wikidata.reconci.link/en/api"],
    licenseClass: "public_api",
    licenseNote:
      "CC0 SPARQL / OpenRefine reconcile. Entity helper only — not a company registry product.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["entity_registry"],
  },
  {
    id: "src_acled",
    name: "ACLED (license gate)",
    family: "disruption",
    observeKind: "disruption_policy",
    channelUse: "pulse",
    day0Tier: "tier_1_5b",
    tierRank: null,
    sourceUrl: "https://acleddata.com/",
    feedUrl: "https://acleddata.com/",
    licenseClass: "paid_license_required",
    licenseNote:
      "ACLED access agreement restricts redistribution. Stub blocked until a human-cleared license is on file.",
    fetchStatus: "license_required",
    existingCollectorId: null,
    signalTypes: ["event_geocoded"],
  },

  // ---- Light Tier C backlog --------------------------------------------
  {
    id: "src_bis_entity_list",
    name: "BIS Entity List",
    family: "disruption",
    observeKind: "disruption_policy",
    channelUse: "both",
    day0Tier: "tier_c",
    tierRank: null,
    sourceUrl:
      "https://www.bis.doc.gov/index.php/policy-guidance/lists-of-parties-of-concern/entity-list",
    feedUrl:
      "https://www.bis.doc.gov/index.php/policy-guidance/lists-of-parties-of-concern/entity-list",
    licenseClass: "public_api",
    licenseNote:
      "Commerce BIS Entity List. Public named entities. Not a screening-product claim.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["sanctions_match"],
    scrapePosture: "file_csv",
  },
  {
    id: "src_bis_denied_persons",
    name: "BIS Denied Persons List",
    family: "disruption",
    observeKind: "disruption_policy",
    channelUse: "both",
    day0Tier: "tier_c",
    tierRank: null,
    sourceUrl:
      "https://www.bis.doc.gov/index.php/policy-guidance/lists-of-parties-of-concern/denied-persons-list",
    feedUrl:
      "https://www.bis.doc.gov/index.php/policy-guidance/lists-of-parties-of-concern/denied-persons-list",
    licenseClass: "public_api",
    licenseNote: "Commerce BIS Denied Persons. Complements Entity List + OFAC SDN.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["sanctions_match"],
    scrapePosture: "file_csv",
  },
  {
    id: "src_fra",
    name: "FRA safety data extras",
    family: "disruption",
    observeKind: "disruption_policy",
    channelUse: "pulse",
    day0Tier: "tier_c",
    tierRank: null,
    sourceUrl: "https://safetydata.fra.dot.gov/",
    feedUrl: "https://safetydata.fra.dot.gov/",
    licenseClass: "public_api",
    licenseNote: "FRA public railroad safety extracts. Light stub.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["event_geocoded"],
    scrapePosture: "file_csv",
  },
  {
    id: "src_stb",
    name: "STB extras",
    family: "freight_commodity",
    observeKind: "logistics_lane",
    channelUse: "api",
    day0Tier: "tier_c",
    tierRank: null,
    sourceUrl: "https://www.stb.gov/",
    feedUrl: "https://www.stb.gov/",
    licenseClass: "public_api",
    licenseNote: "Surface Transportation Board public filings / stats. Light stub.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["freight_rate"],
    scrapePosture: "careful_public_page",
  },
  {
    id: "src_noaa_ports",
    name: "NOAA PORTS",
    family: "freight_commodity",
    observeKind: "logistics_lane",
    channelUse: "pulse",
    day0Tier: "tier_c",
    tierRank: null,
    sourceUrl: "https://tidesandcurrents.noaa.gov/ports.html",
    feedUrl: "https://api.tidesandcurrents.noaa.gov/api/prod/",
    licenseClass: "public_api",
    licenseNote: "NOAA Physical Oceanographic Real-Time System. Public CO-OPS API.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["natural_hazard"],
  },
  {
    id: "src_opencorporates",
    name: "OpenCorporates (ToS gate)",
    family: "filing",
    observeKind: "supplier_public",
    channelUse: "api",
    day0Tier: "tier_c",
    tierRank: null,
    sourceUrl: "https://opencorporates.com/",
    feedUrl: "https://api.opencorporates.com/v0.4/companies/search",
    licenseClass: "free_registration",
    licenseNote:
      "ToS gate — do not live-fetch until legal reviews OpenCorporates terms. Complements GLEIF / CH.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["entity_registry"],
  },
  {
    id: "src_owid",
    name: "Our World in Data cite helper",
    family: "index",
    observeKind: "price_index",
    channelUse: "pulse",
    day0Tier: "tier_c",
    tierRank: null,
    sourceUrl: "https://ourworldindata.org/",
    feedUrl: "https://ourworldindata.org/",
    licenseClass: "public_api",
    licenseNote:
      "Cite helper only. Attribute OWID + underlying source. No invented series.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["economic_index"],
    scrapePosture: "careful_public_page",
  },
  {
    id: "src_uspto_odp",
    name: "USPTO Open Data Portal",
    family: "filing",
    observeKind: "supplier_public",
    channelUse: "api",
    day0Tier: "tier_c",
    tierRank: null,
    sourceUrl: "https://developer.uspto.gov/api-catalog",
    feedUrl: "https://developer.uspto.gov/api-catalog",
    licenseClass: "public_api",
    licenseNote: "USPTO ODP public APIs. Patent/trademark metadata, not tenant IP files.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["corporate_filing"],
  },
  {
    id: "src_ftc_rss",
    name: "FTC / AG RSS",
    family: "news_osint",
    observeKind: "disruption_policy",
    channelUse: "pulse",
    day0Tier: "tier_c",
    tierRank: null,
    sourceUrl: "https://www.ftc.gov/news-events",
    feedUrl: "https://www.ftc.gov/feeds/press-release.xml",
    altFeedUrls: ["https://www.naag.org/news-resources/"],
    licenseClass: "public_api",
    licenseNote:
      "FTC press RSS + state AG headline cites. Headlines + link only.",
    fetchStatus: "stub",
    existingCollectorId: null,
    signalTypes: ["osint_headline"],
    scrapePosture: "rss",
  },

  // ---- Paid commercial — placeholders only ------------------------------
  {
    id: "src_dat",
    name: "DAT freight rates",
    family: "freight_commodity",
    observeKind: "logistics_lane",
    channelUse: "both",
    day0Tier: "license_required",
    tierRank: null,
    sourceUrl: "https://www.dat.com/",
    feedUrl: "https://www.dat.com/",
    licenseClass: "paid_license_required",
    licenseNote: "Commercial truckload rates. Placeholder only.",
    fetchStatus: "license_required",
    existingCollectorId: null,
    signalTypes: ["freight_rate"],
  },
  {
    id: "src_freightos_fbx",
    name: "Freightos Baltic Index (FBX)",
    family: "freight_commodity",
    observeKind: "logistics_lane",
    channelUse: "both",
    day0Tier: "license_required",
    tierRank: null,
    sourceUrl: "https://fbx.freightos.com/",
    feedUrl: "https://fbx.freightos.com/",
    licenseClass: "paid_license_required",
    licenseNote: "Commercial ocean index. Placeholder only.",
    fetchStatus: "license_required",
    existingCollectorId: null,
    signalTypes: ["freight_rate"],
  },
  {
    id: "src_xeneta",
    name: "Xeneta ocean/air benchmarks",
    family: "freight_commodity",
    observeKind: "logistics_lane",
    channelUse: "both",
    day0Tier: "license_required",
    tierRank: null,
    sourceUrl: "https://www.xeneta.com/",
    feedUrl: "https://www.xeneta.com/",
    licenseClass: "paid_license_required",
    licenseNote: "Commercial rate benchmark. Placeholder only.",
    fetchStatus: "license_required",
    existingCollectorId: null,
    signalTypes: ["freight_rate"],
  },
  {
    id: "src_drewry",
    name: "Drewry container / World Container Index",
    family: "freight_commodity",
    observeKind: "logistics_lane",
    channelUse: "both",
    day0Tier: "license_required",
    tierRank: null,
    sourceUrl: "https://www.drewry.co.uk/",
    feedUrl: "https://www.drewry.co.uk/",
    licenseClass: "paid_license_required",
    licenseNote: "Commercial container index. Placeholder only.",
    fetchStatus: "license_required",
    existingCollectorId: null,
    signalTypes: ["freight_rate"],
  },
  {
    id: "src_sonar",
    name: "FreightWaves SONAR",
    family: "freight_commodity",
    observeKind: "logistics_lane",
    channelUse: "both",
    day0Tier: "license_required",
    tierRank: null,
    sourceUrl: "https://sonar.freightwaves.com/",
    feedUrl: "https://sonar.freightwaves.com/",
    licenseClass: "paid_license_required",
    licenseNote: "Commercial freight analytics. Placeholder only.",
    fetchStatus: "license_required",
    existingCollectorId: null,
    signalTypes: ["freight_rate"],
  },
  {
    id: "src_lme",
    name: "London Metal Exchange",
    family: "freight_commodity",
    observeKind: "price_index",
    channelUse: "both",
    day0Tier: "license_required",
    tierRank: null,
    sourceUrl: "https://www.lme.com/",
    feedUrl: "https://www.lme.com/",
    licenseClass: "paid_license_required",
    licenseNote: "Licensed metal prices. Placeholder only.",
    fetchStatus: "license_required",
    existingCollectorId: null,
    signalTypes: ["commodity_index"],
  },
  {
    id: "src_cme",
    name: "CME Group",
    family: "freight_commodity",
    observeKind: "price_index",
    channelUse: "both",
    day0Tier: "license_required",
    tierRank: null,
    sourceUrl: "https://www.cmegroup.com/",
    feedUrl: "https://www.cmegroup.com/",
    licenseClass: "paid_license_required",
    licenseNote: "Licensed futures/settlements. Placeholder only.",
    fetchStatus: "license_required",
    existingCollectorId: null,
    signalTypes: ["commodity_index"],
  },
  {
    id: "src_ism_rob",
    name: "ISM Report On Business",
    family: "index",
    observeKind: "price_index",
    channelUse: "pulse",
    day0Tier: "license_required",
    tierRank: null,
    sourceUrl:
      "https://www.ismworld.org/supply-management-news-and-reports/reports/ism-report-on-business/",
    feedUrl:
      "https://www.ismworld.org/supply-management-news-and-reports/reports/ism-report-on-business/",
    licenseClass: "paid_license_required",
    licenseNote: "ISM PMI / ROB is licensed. Placeholder only.",
    fetchStatus: "license_required",
    existingCollectorId: null,
    signalTypes: ["economic_index"],
  },
  {
    id: "src_sp_commodity_index",
    name: "S&P Commodity Insights",
    family: "index",
    observeKind: "price_index",
    channelUse: "both",
    day0Tier: "license_required",
    tierRank: null,
    sourceUrl: "https://www.spglobal.com/commodityinsights/",
    feedUrl: "https://www.spglobal.com/commodityinsights/",
    licenseClass: "paid_license_required",
    licenseNote: "S&P CI commercial prices. Placeholder only.",
    fetchStatus: "license_required",
    existingCollectorId: null,
    signalTypes: ["commodity_index"],
  },
  {
    id: "src_fastmarkets",
    name: "Fastmarkets",
    family: "index",
    observeKind: "price_index",
    channelUse: "both",
    day0Tier: "license_required",
    tierRank: null,
    sourceUrl: "https://www.fastmarkets.com/",
    feedUrl: "https://www.fastmarkets.com/",
    licenseClass: "paid_license_required",
    licenseNote: "Commercial price assessments. Placeholder only.",
    fetchStatus: "license_required",
    existingCollectorId: null,
    signalTypes: ["commodity_index"],
  },
  {
    id: "src_joc",
    name: "Journal of Commerce",
    family: "freight_commodity",
    observeKind: "logistics_lane",
    channelUse: "pulse",
    day0Tier: "license_required",
    tierRank: null,
    sourceUrl: "https://www.joc.com/",
    feedUrl: "https://www.joc.com/",
    licenseClass: "paid_license_required",
    licenseNote: "JOC commercial news/data. Placeholder only.",
    fetchStatus: "license_required",
    existingCollectorId: null,
    signalTypes: ["freight_rate"],
  },
] as const;

const SOURCE_BY_ID = new Map(DATA_FACTORY_SOURCES.map((s) => [s.id, s]));

export function getDataFactorySource(
  id: string,
): DataFactorySource | undefined {
  return SOURCE_BY_ID.get(id);
}

export function listDataFactorySources(filter?: {
  family?: DataFactorySourceFamily;
  fetchStatus?: DataFactoryFetchStatus;
  licenseClass?: DataFactoryLicenseClass;
  day0Tier?: DataFactoryDay0Tier;
  channelUse?: DataFactoryChannelUse;
}): DataFactorySource[] {
  return DATA_FACTORY_SOURCES.filter((s) => {
    if (filter?.family && s.family !== filter.family) return false;
    if (filter?.fetchStatus && s.fetchStatus !== filter.fetchStatus) {
      return false;
    }
    if (filter?.licenseClass && s.licenseClass !== filter.licenseClass) {
      return false;
    }
    if (filter?.day0Tier && s.day0Tier !== filter.day0Tier) return false;
    if (filter?.channelUse) {
      if (filter.channelUse === "both") {
        if (s.channelUse !== "both") return false;
      } else if (
        s.channelUse !== filter.channelUse &&
        s.channelUse !== "both"
      ) {
        return false;
      }
    }
    return true;
  });
}

export function listTier1Sources(): DataFactorySource[] {
  return listDataFactorySources({ day0Tier: "tier_1" }).sort(
    (a, b) => (a.tierRank ?? 99) - (b.tierRank ?? 99),
  );
}

export function listTier2Sources(): DataFactorySource[] {
  return listDataFactorySources({ day0Tier: "tier_2" });
}

export function listTier15Sources(): DataFactorySource[] {
  return TIER15_SOURCE_IDS.map((id) => {
    const source = getDataFactorySource(id);
    if (!source) {
      throw new Error(`TIER15_SOURCE_IDS missing catalog row ${id}`);
    }
    return source;
  });
}

export function listTier15bSources(): DataFactorySource[] {
  return TIER15B_SOURCE_IDS.map((id) => {
    const source = getDataFactorySource(id);
    if (!source) {
      throw new Error(`TIER15B_SOURCE_IDS missing catalog row ${id}`);
    }
    return source;
  });
}

export function listTierCSources(): DataFactorySource[] {
  return TIER_C_SOURCE_IDS.map((id) => {
    const source = getDataFactorySource(id);
    if (!source) {
      throw new Error(`TIER_C_SOURCE_IDS missing catalog row ${id}`);
    }
    return source;
  });
}

export function listNewsOsintSources(): DataFactorySource[] {
  return NEWS_OSINT_SOURCE_IDS.map((id) => {
    const source = getDataFactorySource(id);
    if (!source) {
      throw new Error(`NEWS_OSINT_SOURCE_IDS missing catalog row ${id}`);
    }
    return source;
  });
}

/** @deprecated use listTier1Sources */
export function listWireFirstSources(): DataFactorySource[] {
  return listTier1Sources();
}
