// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/HomeCalmExec.tsx": () => import("../components/mockups/HomeCalmExec.tsx"),
  "./components/mockups/HomeStatusBoard.tsx": () => import("../components/mockups/HomeStatusBoard.tsx"),
  "./components/mockups/HomeTriageFirst.tsx": () => import("../components/mockups/HomeTriageFirst.tsx")
};
